apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    tier: database-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db
      tier: database
  serviceName: mongo
  template:
    metadata:
      name: mongodb
      labels:
        type: db
        tier: database
    spec:
      containers:
        - name: mongodb
          image: ghcr.io/saketh-macharla/assignment-mongo:latest
          ports:
            - containerPort: 27017
  #         volumeMounts:
  #           - mountPath: /data/db
  #             name: mongodb-persistent-storage-claim
  # volumeClaimTemplates:
  #   - metadata:
  #       name: mongodb-persistent-storage-claim
  #     spec:
  #       storageClassName: gpe-storageclass
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi