# Default values for voting-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


deploy:
  name: 
    fe: fe-deployment
    api: go-api-deployment
    db: mongo
  containerName:
    fe: fe-react-app
    api: go-api-pod
    db: mongodb
  replicaCount:
    fe: 3
    api: 1
    db: 3
  image:
    repository: ghcr.io
    owner: saketh-macharla
    # Overrides the image tag whose default is the chart appVersion.
    tag:
      fe: 1234
      api: 1234
    imagePullSecrets: ghcr-secret
    imagePullPolicy: Always
    imageName:
      api: voting-be
      fe: voting-fe
      db: assignment-mongo
  ports:
    fe: 3000
    api: 8080
    db: 27017




service:
    name:
      fe: fe-service
      api: go-api-service
      db: mongo
    type:
      fe: NodePort
    ports:
      fe:
        nodePort: 30004
        port: 3000
      api:
        port: 8080
      db:
        port: 27017

domian: react-go.tk
subdomain: backend.react-go.tk





