apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.service.name.api }}
  labels:
  {{- template "common-label" }}
spec:
  ports:
  {{- with .Values.service.ports }}
    - targetPort: {{ .api.port }}
      port: {{ .api.port }}
  {{- end }}
  selector:
  {{- template "api-labels"}}