apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name.db }}
  labels:
  {{- template "db-labels" }}
spec:
  ports:
  {{- with .Values.service.ports }}
  - port: {{ .db.port }}
    targetPort: {{ .db.port }}
  {{- end }}
  clusterIP: None
  selector:
  {{- template "db-labels" }}