apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.deploy.name.db }}
  labels:
    tier: database-statefulset
spec:
  replicas: {{ .Values.deploy.replicaCount.db }}
  selector:
    matchLabels:
    {{- include "db-labels" . | indent 2}}
  serviceName: mongo
  template:
    metadata:
      name: mongodb
      labels:
      {{- include "db-labels" . | indent 4}}
    spec:
      containers:
        - name: {{ .Values.deploy.containerName.db }}
          image: "{{ .Values.deploy.image.repository }}/{{ .Values.deploy.image.owner }}/{{ .Values.deploy.image.imageName.db }}:latest"
          ports:
            - containerPort: {{ .Values.deploy.ports.db }}
      # No need for this for now as the image in ghcr is public.
      # you have to use this secret if the image is private
      # imagePullSecrets: 
      #   - name: ghcr-secret
