apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.domian }}
      http: 
        paths:
          - backend:
              service:
                name: {{ .Values.service.name.fe }}
                port:
                  number: {{ .Values.service.ports.fe.port }}
            pathType: Prefix
            path: /
    - host: {{ .Values.subdomain }}
      http: 
        paths:
          - backend:
              service:
                name: {{ .Values.service.name.api }}
                port:
                  number: {{ .Values.service.ports.api.port }}
            pathType: Prefix
            path: /
          