name: Voting App Deploy

on:
  workflow_run:
    workflows: [Voting App Build]
    types: ["completed"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}}
    - name: Kubectl config for the cluster
      run: aws eks update-kubeconfig --name MyCluster --region ${{secrets.AWS_REGION}}
    - name: Deploy
      run: |
        kubectl set image deployment/fe-deployment fe-react-app=ghcr.io/${{secrets.GIT_USERNAME}}/voting-fe:${{ github.sha }}
        kubectl set image deployment/go-api-deployment go-api-pod=ghcr.io/${{secrets.GIT_USERNAME}}/voting-be:${{ github.sha }}
    - name: Deployment status
      run: |
        kubectl rollout status deployment/fe-deployment
        kubectl rollout status deployment/go-api-deployment
    - name: Deleting config file - ~/.kube
      run: rm -r ~/.kube



    