name: Voting App Deploy

on:
  workflow_run:
    workflows: [Voting App Build]
    types: ["completed"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}}
    - name: Kubectl config for the cluster
      run: aws eks update-kubeconfig --name MyCluster --region ${{secrets.AWS_REGION}}
    - name: Deploy
      run: |
        helm upgrade --set deploy.image.tag.fe=${{ github.sha }} --set deploy.image.tag.api=${{ github.sha }} voting-app ./voting-chart
    - name: Deployment status
      run: |
        kubectl rollout status deployment/fe-deployment
        kubectl rollout status deployment/go-api-deployment
    - name: Deleting config file - ~/.kube
      run: rm -r ~/.kube



    